<?php
/* DATABASE DEFAULT TABLE CREATED */

$sql_rq1 = "CREATE TABLE tabledefault (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pseudo VARCHAR(220) NOT NULL,
    email VARCHAR(220) NOT NULL,
    passwordd VARCHAR(220) NOT NULL,
    datee TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )";


?>